"""add role column to users table

Revision ID: c201fe9340a3
Revises: b02d1acd707d
Create Date: 2026-05-25 23:20:40.497403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c201fe9340a3'
down_revision: Union[str, Sequence[str], None] = 'b02d1acd707d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False))
    # 更新已有的 admin 用户角色
    op.execute("UPDATE users SET role = 'admin' WHERE name = 'admin'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
